version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Install dependencies
          command: yarn

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn build

      - persist_to_workspace:
          root: '.'
          paths:
            - build
            - yarn.lock

  test:
    docker:
      - image: circleci/node:7.10
    steps:
      - checkout
      - attach_workspace:
          at: '.'
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run: yarn test

  deploy:
    docker:
      - image: circleci/node:7.10
    steps:
      - checkout
      - attach_workspace:
          at: '.'
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - add_ssh_keys:
          fingerprints:
            - "fb:30:a4:41:71:38:18:6f:11:eb:10:c4:f3:b8:07:ac"
      - run: yarn deploy-ci

workflows:
  version: 2
  build_test:
    jobs:
      - build
      - test:
          requires:
            - build
  build_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master